spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
spring:
  application:
    name: employee-provider
  profiles: dev
---
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
spring:
  application:
    name: employee-provider
  profiles: test
---
